export const VALID_MOVEMENT_PATTERNS = [
  'horizontal_push',
  'vertical_push',
  'horizontal_pull',
  'vertical_pull',
  'squat_pattern',
  'hip_hinge',
  'knee_flexion',
  'knee_extension',
  'calf_raise',
  'wrist_flexion',
  'wrist_extension',
  'forearm_rotation',
  'elbow_flexion',
  'elbow_extension',
  'lateral_raise',
  'hip_abduction',
  'hip_adduction',
  'shoulder_rotation',
  'carry',
  'scapular_elevation',
  'scapular_retraction',
  'scapular_protraction',
  'core_anti_flex',
  'core_flex',
  'core_rotation',
] as const

export const VALID_MOVEMENT_PATTERN_SET = new Set<string>(VALID_MOVEMENT_PATTERNS)
